### ISSUE TITLE
useTx repeatedly queries txInfo after broadcast and invokes the onError handler each time if the tx failed on the network

### ISSUE THREAD

**Issue by jimryan** [leyetilabs/wizard-ui#3]
@arthuryeti I haven't dug too deep into this yet, but I'm seeing some buggy behavior.

When a transaction is made via useTx, the txInfo API request is [made repeatedly](https://github.com/arthuryeti/terra/blob/v1.6.1/src/hooks/useTx.ts#L70-L83). I think this has something to do with react-query's [default](https://react-query.tanstack.com/guides/important-defaults) refetch behavior. I can reliably trigger it by refocusing the window or disconnecting/reconnecting the network, for example. 

This alone is just a minor issue until you have a transaction that fails on the network. In that scenario, the onError handler is [invoked](https://github.com/arthuryeti/terra/blob/v1.6.1/src/hooks/useTx.ts#L99-L107) _each_ time the txInfo is refetched.

**Worse, onError is immediately called anytime a new tx is submitted. This is because the txHash is [cleared](https://github.com/arthuryeti/terra/blob/v1.6.1/src/hooks/useTx.ts#L39), which is a [dependency](https://github.com/arthuryeti/terra/blob/v1.6.1/src/hooks/useTx.ts#L107) on the effect that [invokes](https://github.com/arthuryeti/terra/blob/v1.6.1/src/hooks/useTx.ts#L102) onError.**

I'm not sure on the best way to proceed, so here are my thoughts:
- While it's very cool for the `useTx` hook to track the transaction after broadcast, I wonder how useful it is in practice. We don't really know how long the tx will be queued. I'd think most apps would want to let their users do something else in the interim. I could see an argument that this hook makes it easy for them to do it, so they could track the tx state in the same component that initiated it, and the user could simply abandon it if they so wish, but still, I wonder if that use-case is worth maintaining this, which is going to run into all sorts of edge cases. 

  So perhaps the scope of `useTx` should be reduced to end at broadcast. The onSuccess handler (or onBroadcast) could be invoked with the txHash and then the user can decide what to do from there. They could simply use `useTxInfo` if they want to track it beyond that, or they can pass it to another part of their app to track it at a higher level (e.g. a notification center). 
- Another argument for this is the behavior when a second transaction is created while the first is still pending. Callbacks will never be called for the first transaction. That's unintuitive for the user.
- If removing this functionality is not an option, then it should be fixed:
  - One option:
    - Once a txInfo response is received, maybe the hook should "reset" by clearing its txHash state?
    - If we did that, it should then stop exposing the txHash state. It would be for exclusive internal use by the hook.
    - Instead, the txHash should be passed to the consumer via one of the callbacks (which is already the case). The consumer can then do whatever it wants with it. 
  - Another option:
    - Store the txInfo or some boolean indicating that it was received in state, and disable the query when it's set.
    - Invoke the onError/onSuccess handlers from the useQuery onSuccess handler (instead of the effect).
    - Reset the txInfo/boolean from first point when `submit` is called, or in onMutate (this will reenable the query once a txHash is set for the new tx)
- I'm sure there are other options as well, these are just what came to mind immediately.

**Comment by arthuryeti** [comment]
@jimryan I'm pushing an update with the query removed, so it should fix all the edge cases. We can use useTxInfo to create notifications.
