### ISSUE TITLE
Error executing contract with a hardware wallet

### ISSUE THREAD

**Issue by dougcalc** [leyetilabs/wizard-ui#6]
Hey mate!

I'm getting error messages like `Reason: Data is invalid : Unexpected characters` and `context invalidated` when executing a contract via a hardware wallet (like Ledger). Execution is otherwise working well. Wondering if you've come across this and if there's a way to solve it?

Doug

**Comment by arthuryeti** [comment]
Hey @dougcalc 

Fixed on version 1.4.0 with this commit https://github.com/leyetilabs/wizard-ui/commit/0a2651899e2aece30edefbe4dc5174c0c9d51f12
